### ISSUE TITLE
Generate routes and starter page source from YAML

### ISSUE THREAD

**Issue by jfilby** [jfilby/nexus#2]
This will be optional, but could save a lot of time.

I've written a prototype example of what the YAML could look like:

```
%YAML 1.2
---

- name: Frontpage
  description: This is the frontpage of my application.
  module: Online Store
  routeOptions: AllowGet
  pageOptions: [ get ]
  route:
  - s: /
    type: path
  parameters:
  - name: m
    type: bool
    constraints: []
  defaults:
  - field: m
    default: True
  modelFields: []


- name: Order
  description: Order page
  module: Online Store
  routeOptions: AllowGetPost
  pageOptions: [ get,
                 post,
                 getModelRecords ]
  route:
  - s: /orders/{Order No}
    type: path
  parameters:
  - name: Order No
    type: string
    constraints: [ not null ]
  defaults: []
  modelFields: 
  - name: Order No
    field: Order.Order No
```
